package utils

import (
	"log"
	"time"

	"credit_app/models"

	"gorm.io/gorm"
)

func CreateTestData(db *gorm.DB) {
	log.Println("Creating test applications...")

	testApplications := []models.CreditApplication{
		// ПК - Потребительский кредит
		{
			ID:                     "ПК-12345678-01-01",
			ClientName:             "Иванов Иван Иванович",
			FullName:               "Иванов Иван Иванович",
			BirthDate:              ptrTime(time.Date(1985, 3, 15, 0, 0, 0, 0, time.UTC)),
			Age:                    41,
			Phone:                  "+7 (999) 123-45-67",
			Email:                  "ivanov.ivan@example.com",
			PassportSeries:         "1234",
			PassportNumber:         "567890",
			PassportIssueDate:      ptrTime(time.Date(2020, 5, 20, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "123-456",
			RegistrationAddress:    "г. Москва, ул. Ленина, д. 10, кв. 5",
			ResidenceAddress:       "г. Москва, ул. Ленина, д. 10, кв. 5",
			RequestedAmount:        500000,
			CreditTerm:             24,
			CreditType:             "ПК",
			MonthlyIncome:          85000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "ООО Ромашка",
			Position:               "Менеджер",
			CurrentJobExperience:   "3 года",
			TotalExperience:        "10 лет",
			Status:                 "approved",
			Priority:               "medium",
			CreditScore:            720,
			TotalCredits:           2,
			ActiveCredits:          1,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              150000,
			DTIRatio:               0.18,
			AvailableCreditLimit:   300000,
			ActiveCreditsList:      "[{\"type\":\"Потребительский кредит\",\"amount\":150000,\"monthlyPayment\":7000}]",
			ApprovedAmount:         500000,
			InitialScore:           750,
			CreditHistoryScore:     70,
			IncomeStabilityScore:   80,
			DebtBurdenScore:        75,
			AgeFactorScore:         70,
			EmploymentScore:        85,
			SolvabilityScore:       78,
			RiskScore:              75,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-7 * 24 * time.Hour),
		},
		{
			ID:                     "ПК-87654321-02-02",
			ClientName:             "Петрова Анна Сергеевна",
			FullName:               "Петрова Анна Сергеевна",
			BirthDate:              ptrTime(time.Date(1990, 7, 22, 0, 0, 0, 0, time.UTC)),
			Age:                    35,
			Phone:                  "+7 (987) 654-32-10",
			Email:                  "petrova.anna@example.com",
			PassportSeries:         "5678",
			PassportNumber:         "123456",
			PassportIssueDate:      ptrTime(time.Date(2019, 3, 15, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "456-789",
			RegistrationAddress:    "г. Москва, ул. Пушкина, д. 25, кв. 12",
			ResidenceAddress:       "г. Москва, ул. Пушкина, д. 25, кв. 12",
			RequestedAmount:        300000,
			CreditTerm:             18,
			CreditType:             "ПК",
			MonthlyIncome:          65000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "ООО Ландыш",
			Position:               "Бухгалтер",
			CurrentJobExperience:   "5 лет",
			TotalExperience:        "12 лет",
			Status:                 "in_review",
			Priority:               "high",
			CreditScore:            690,
			TotalCredits:           1,
			ActiveCredits:          0,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              0,
			DTIRatio:               0.15,
			AvailableCreditLimit:   200000,
			ActiveCreditsList:      "[{\"type\":\"Кредитная карта\",\"amount\":50000,\"monthlyPayment\":2000}]",
			ApprovedAmount:         0,
			InitialScore:           720,
			CreditHistoryScore:     68,
			IncomeStabilityScore:   75,
			DebtBurdenScore:        72,
			AgeFactorScore:         75,
			EmploymentScore:        80,
			SolvabilityScore:       72,
			RiskScore:              72,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-4 * 24 * time.Hour),
		},
		// АК - Автокредит
		{
			ID:                     "АК-11223344-03-03",
			ClientName:             "Сидоров Дмитрий Александрович",
			FullName:               "Сидоров Дмитрий Александрович",
			BirthDate:              ptrTime(time.Date(1988, 11, 5, 0, 0, 0, 0, time.UTC)),
			Age:                    37,
			Phone:                  "+7 (912) 345-67-89",
			Email:                  "sidorov.dmitry@example.com",
			PassportSeries:         "9012",
			PassportNumber:         "345678",
			PassportIssueDate:      ptrTime(time.Date(2018, 8, 10, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "789-012",
			RegistrationAddress:    "г. Санкт-Петербург, пр. Невский, д. 50",
			ResidenceAddress:       "г. Санкт-Петербург, пр. Невский, д. 50",
			RequestedAmount:        1500000,
			CreditTerm:             36,
			CreditType:             "АК",
			MonthlyIncome:          120000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "АО Солнце",
			Position:               "Инженер",
			CurrentJobExperience:   "7 лет",
			TotalExperience:        "15 лет",
			Status:                 "approved",
			Priority:               "medium",
			CreditScore:            760,
			TotalCredits:           2,
			ActiveCredits:          1,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              400000,
			DTIRatio:               0.22,
			AvailableCreditLimit:   200000,
			ActiveCreditsList:      "[{\"type\":\"Автокредит\",\"amount\":400000,\"monthlyPayment\":15000}]",
			ApprovedAmount:         1500000,
			InitialScore:           780,
			CreditHistoryScore:     75,
			IncomeStabilityScore:   85,
			DebtBurdenScore:        75,
			AgeFactorScore:         75,
			EmploymentScore:        80,
			SolvabilityScore:       78,
			RiskScore:              78,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-10 * 24 * time.Hour),
		},
		// ИП - Ипотека
		{
			ID:                     "ИП-99887766-04-04",
			ClientName:             "Козлова Марина Владимировна",
			FullName:               "Козлова Марина Владимировна",
			BirthDate:              ptrTime(time.Date(1987, 4, 18, 0, 0, 0, 0, time.UTC)),
			Age:                    39,
			Phone:                  "+7 (923) 456-78-90",
			Email:                  "kozlova.marina@example.com",
			PassportSeries:         "3456",
			PassportNumber:         "789012",
			PassportIssueDate:      ptrTime(time.Date(2017, 6, 25, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "234-567",
			RegistrationAddress:    "г. Москва, ул. Гагарина, д. 15, кв. 8",
			ResidenceAddress:       "г. Москва, ул. Гагарина, д. 15, кв. 8",
			RequestedAmount:        5000000,
			CreditTerm:             240,
			CreditType:             "ИП",
			MonthlyIncome:          180000,
			EmploymentStatus:       "Руководитель",
			EmployerName:           "ООО Весна",
			Position:               "Директор",
			CurrentJobExperience:   "8 лет",
			TotalExperience:        "18 лет",
			Status:                 "in_review",
			Priority:               "high",
			CreditScore:            810,
			TotalCredits:           3,
			ActiveCredits:          2,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              1200000,
			DTIRatio:               0.28,
			AvailableCreditLimit:   500000,
			ActiveCreditsList:      "[{\"type\":\"Потребительский кредит\",\"amount\":500000,\"monthlyPayment\":20000},{\"type\":\"Ипотека\",\"amount\":700000,\"monthlyPayment\":35000}]",
			ApprovedAmount:         0,
			InitialScore:           850,
			CreditHistoryScore:     85,
			IncomeStabilityScore:   90,
			DebtBurdenScore:        80,
			AgeFactorScore:         75,
			EmploymentScore:        95,
			SolvabilityScore:       85,
			RiskScore:              82,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-3 * 24 * time.Hour),
		},
		// КК - Кредитная карта
		{
			ID:                     "КК-55667788-05-05",
			ClientName:             "Волков Сергей Николаевич",
			FullName:               "Волков Сергей Николаевич",
			BirthDate:              ptrTime(time.Date(1992, 9, 30, 0, 0, 0, 0, time.UTC)),
			Age:                    33,
			Phone:                  "+7 (934) 567-89-01",
			Email:                  "volkov.sergey@example.com",
			PassportSeries:         "7890",
			PassportNumber:         "123456",
			PassportIssueDate:      ptrTime(time.Date(2021, 2, 14, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "345-678",
			RegistrationAddress:    "г. Екатеринбург, ул. Мира, д. 30",
			ResidenceAddress:       "г. Екатеринбург, ул. Мира, д. 30",
			RequestedAmount:        200000,
			CreditTerm:             12,
			CreditType:             "КК",
			MonthlyIncome:          75000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "ИП Волков С.Н.",
			Position:               "Предприниматель",
			CurrentJobExperience:   "4 года",
			TotalExperience:        "8 лет",
			Status:                 "rejected",
			Priority:               "low",
			CreditScore:            650,
			TotalCredits:           1,
			ActiveCredits:          0,
			ClosedCredits:          1,
			DelayedPayments12m:     1,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     15,
			TotalDebt:              0,
			DTIRatio:               0.12,
			AvailableCreditLimit:   150000,
			ActiveCreditsList:      "[]",
			ApprovedAmount:         0,
			InitialScore:           680,
			CreditHistoryScore:     60,
			IncomeStabilityScore:   70,
			DebtBurdenScore:        68,
			AgeFactorScore:         80,
			EmploymentScore:        72,
			SolvabilityScore:       65,
			RiskScore:              65,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		// БК - Бизнес-кредит
		{
			ID:                     "БК-44332211-06-06",
			ClientName:             "Морозов Алексей Петрович",
			FullName:               "Морозов Алексей Петрович",
			BirthDate:              ptrTime(time.Date(1983, 12, 8, 0, 0, 0, 0, time.UTC)),
			Age:                    42,
			Phone:                  "+7 (945) 678-90-12",
			Email:                  "morozov.alexey@example.com",
			PassportSeries:         "1122",
			PassportNumber:         "334455",
			PassportIssueDate:      ptrTime(time.Date(2016, 9, 5, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "567-890",
			RegistrationAddress:    "г. Казань, ул. Баумана, д. 22",
			ResidenceAddress:       "г. Казань, ул. Баумана, д. 22",
			RequestedAmount:        3000000,
			CreditTerm:             36,
			CreditType:             "БК",
			MonthlyIncome:          250000,
			EmploymentStatus:       "Индивидуальный предприниматель",
			EmployerName:           "ИП Морозов А.П.",
			Position:               "Директор",
			CurrentJobExperience:   "10 лет",
			TotalExperience:        "15 лет",
			Status:                 "approved",
			Priority:               "high",
			CreditScore:            790,
			TotalCredits:           4,
			ActiveCredits:          2,
			ClosedCredits:          2,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              1800000,
			DTIRatio:               0.32,
			AvailableCreditLimit:   800000,
			ActiveCreditsList:      "[{\"type\":\"Бизнес-кредит\",\"amount\":800000,\"monthlyPayment\":30000},{\"type\":\"Овердрафт\",\"amount\":1000000,\"monthlyPayment\":40000}]",
			ApprovedAmount:         3000000,
			InitialScore:           820,
			CreditHistoryScore:     80,
			IncomeStabilityScore:   85,
			DebtBurdenScore:        78,
			AgeFactorScore:         70,
			EmploymentScore:        90,
			SolvabilityScore:       82,
			RiskScore:              80,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-5 * 24 * time.Hour),
		},
		// Отклоненные заявки
		{
			ID:                     "ПК-22334455-07-07",
			ClientName:             "Смирнова Екатерина Андреевна",
			FullName:               "Смирнова Екатерина Андреевна",
			BirthDate:              ptrTime(time.Date(1995, 6, 12, 0, 0, 0, 0, time.UTC)),
			Age:                    30,
			Phone:                  "+7 (967) 890-12-34",
			Email:                  "smirnova.ekaterina@example.com",
			PassportSeries:         "8899",
			PassportNumber:         "001122",
			PassportIssueDate:      ptrTime(time.Date(2022, 1, 20, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "123-456",
			RegistrationAddress:    "г. Сочи, ул. Набережная, д. 8",
			ResidenceAddress:       "г. Сочи, ул. Набережная, д. 8",
			RequestedAmount:        250000,
			CreditTerm:             12,
			CreditType:             "ПК",
			MonthlyIncome:          45000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "ООО Луч",
			Position:               "Специалист",
			CurrentJobExperience:   "2 года",
			TotalExperience:        "5 лет",
			Status:                 "rejected",
			Priority:               "low",
			CreditScore:            580,
			TotalCredits:           3,
			ActiveCredits:          2,
			ClosedCredits:          1,
			DelayedPayments12m:     3,
			CurrentDelinquencies:   true,
			MaxDelinquencyDays:     45,
			TotalDebt:              280000,
			DTIRatio:               0.55,
			AvailableCreditLimit:   0,
			ActiveCreditsList:      "[{\"type\":\"Кредитная карта\",\"amount\":80000,\"monthlyPayment\":5000},{\"type\":\"Микрозайм\",\"amount\":200000,\"monthlyPayment\":25000}]",
			ApprovedAmount:         0,
			InitialScore:           580,
			CreditHistoryScore:     45,
			IncomeStabilityScore:   55,
			DebtBurdenScore:        35,
			AgeFactorScore:         65,
			EmploymentScore:        60,
			SolvabilityScore:       45,
			RiskScore:              45,
			AIRecommendation:       "reject",
			PositiveFactors:        "Стабильная работа",
			RiskFactors:            "Высокий уровень задолженности, текущие просрочки",
			CreatedAt:              time.Now().Add(-2 * 24 * time.Hour),
		},
		{
			ID:                     "АК-33445566-08-08",
			ClientName:             "Никитин Олег Михайлович",
			FullName:               "Никитин Олег Михайлович",
			BirthDate:              ptrTime(time.Date(1980, 2, 28, 0, 0, 0, 0, time.UTC)),
			Age:                    46,
			Phone:                  "+7 (978) 901-23-45",
			Email:                  "nikitin.oleg@example.com",
			PassportSeries:         "5566",
			PassportNumber:         "778899",
			PassportIssueDate:      ptrTime(time.Date(2015, 7, 15, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "789-012",
			RegistrationAddress:    "г. Новосибирск, ул. Красная, д. 40",
			ResidenceAddress:       "г. Новосибирск, ул. Красная, д. 40",
			RequestedAmount:        2000000,
			CreditTerm:             60,
			CreditType:             "АК",
			MonthlyIncome:          90000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "АО АвтоПром",
			Position:               "Механик",
			CurrentJobExperience:   "12 лет",
			TotalExperience:        "25 лет",
			Status:                 "rejected",
			Priority:               "medium",
			CreditScore:            610,
			TotalCredits:           5,
			ActiveCredits:          3,
			ClosedCredits:          2,
			DelayedPayments12m:     2,
			CurrentDelinquencies:   true,
			MaxDelinquencyDays:     60,
			TotalDebt:              950000,
			DTIRatio:               0.65,
			AvailableCreditLimit:   0,
			ActiveCreditsList:      "[{\"type\":\"Автокредит\",\"amount\":500000,\"monthlyPayment\":18000},{\"type\":\"Потребительский кредит\",\"amount\":300000,\"monthlyPayment\":12000},{\"type\":\"Кредитная карта\",\"amount\":150000,\"monthlyPayment\":0}]",
			ApprovedAmount:         0,
			InitialScore:           620,
			CreditHistoryScore:     50,
			IncomeStabilityScore:   65,
			DebtBurdenScore:        40,
			AgeFactorScore:         55,
			EmploymentScore:        70,
			SolvabilityScore:       50,
			RiskScore:              48,
			AIRecommendation:       "reject",
			PositiveFactors:        "Большой опыт работы",
			RiskFactors:            "Высокая закредитованность, просрочки",
			CreatedAt:              time.Now().Add(-8 * 24 * time.Hour),
		},
		// Новые заявки
		{
			ID:                     "ПК-44556677-09-09",
			ClientName:             "Лебедева Наталья Викторовна",
			FullName:               "Лебедева Наталья Викторовна",
			BirthDate:              ptrTime(time.Date(1988, 8, 14, 0, 0, 0, 0, time.UTC)),
			Age:                    37,
			Phone:                  "+7 (989) 012-34-56",
			Email:                  "lebedeva.natalia@example.com",
			PassportSeries:         "6677",
			PassportNumber:         "889900",
			PassportIssueDate:      ptrTime(time.Date(2019, 4, 10, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "234-567",
			RegistrationAddress:    "г. Ростов-на-Дону, ул. Буденного, д. 18",
			ResidenceAddress:       "г. Ростов-на-Дону, ул. Буденного, д. 18",
			RequestedAmount:        800000,
			CreditTerm:             30,
			CreditType:             "ПК",
			MonthlyIncome:          95000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "АО Звезда",
			Position:               "Маркетолог",
			CurrentJobExperience:   "6 лет",
			TotalExperience:        "12 лет",
			Status:                 "approved",
			Priority:               "medium",
			CreditScore:            730,
			TotalCredits:           2,
			ActiveCredits:          1,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              200000,
			DTIRatio:               0.20,
			AvailableCreditLimit:   250000,
			ActiveCreditsList:      "[{\"type\":\"Кредитная карта\",\"amount\":200000,\"monthlyPayment\":8000}]",
			ApprovedAmount:         800000,
			InitialScore:           760,
			CreditHistoryScore:     72,
			IncomeStabilityScore:   80,
			DebtBurdenScore:        75,
			AgeFactorScore:         75,
			EmploymentScore:        85,
			SolvabilityScore:       78,
			RiskScore:              75,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "ИП-55667788-10-10",
			ClientName:             "Федоров Игорь Станиславович",
			FullName:               "Федоров Игорь Станиславович",
			BirthDate:              ptrTime(time.Date(1986, 1, 25, 0, 0, 0, 0, time.UTC)),
			Age:                    40,
			Phone:                  "+7 (990) 123-45-67",
			Email:                  "fedorov.igor@example.com",
			PassportSeries:         "7788",
			PassportNumber:         "990011",
			PassportIssueDate:      ptrTime(time.Date(2018, 11, 30, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "345-678",
			RegistrationAddress:    "г. Уфа, ул. Ленина, д. 55",
			ResidenceAddress:       "г. Уфа, ул. Ленина, д. 55",
			RequestedAmount:        4500000,
			CreditTerm:             180,
			CreditType:             "ИП",
			MonthlyIncome:          200000,
			EmploymentStatus:       "Индивидуальный предприниматель",
			EmployerName:           "ИП Федоров И.С.",
			Position:               "Предприниматель",
			CurrentJobExperience:   "7 лет",
			TotalExperience:        "15 лет",
			Status:                 "new",
			Priority:               "high",
			CreditScore:            800,
			TotalCredits:           3,
			ActiveCredits:          2,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              1100000,
			DTIRatio:               0.30,
			AvailableCreditLimit:   600000,
			ActiveCreditsList:      "[{\"type\":\"Ипотека\",\"amount\":800000,\"monthlyPayment\":40000},{\"type\":\"Бизнес-кредит\",\"amount\":300000,\"monthlyPayment\":0}]",
			ApprovedAmount:         0,
			InitialScore:           830,
			CreditHistoryScore:     82,
			IncomeStabilityScore:   88,
			DebtBurdenScore:        78,
			AgeFactorScore:         72,
			EmploymentScore:        92,
			SolvabilityScore:       84,
			RiskScore:              82,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-2 * 24 * time.Hour),
		},
		{
			ID:                     "КК-66778899-11-11",
			ClientName:             "Григорьева Светлана Петровна",
			FullName:               "Григорьева Светлана Петровна",
			BirthDate:              ptrTime(time.Date(1993, 5, 19, 0, 0, 0, 0, time.UTC)),
			Age:                    32,
			Phone:                  "+7 (991) 234-56-78",
			Email:                  "grigorieva.svetlana@example.com",
			PassportSeries:         "8899",
			PassportNumber:         "112233",
			PassportIssueDate:      ptrTime(time.Date(2020, 8, 25, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "456-789",
			RegistrationAddress:    "г. Пермь, ул. Куйбышева, д. 12",
			ResidenceAddress:       "г. Пермь, ул. Куйбышева, д. 12",
			RequestedAmount:        150000,
			CreditTerm:             12,
			CreditType:             "КК",
			MonthlyIncome:          55000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "ООО Метеор",
			Position:               "Секретарь",
			CurrentJobExperience:   "3 года",
			TotalExperience:        "7 лет",
			Status:                 "approved",
			Priority:               "low",
			CreditScore:            680,
			TotalCredits:           1,
			ActiveCredits:          0,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              0,
			DTIRatio:               0.10,
			AvailableCreditLimit:   180000,
			ActiveCreditsList:      "[]",
			ApprovedAmount:         350000,
			InitialScore:           710,
			CreditHistoryScore:     65,
			IncomeStabilityScore:   70,
			DebtBurdenScore:        72,
			AgeFactorScore:         82,
			EmploymentScore:        75,
			SolvabilityScore:       70,
			RiskScore:              70,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "АК-77889900-12-12",
			ClientName:             "Дмитриев Вадим Сергеевич",
			FullName:               "Дмитриев Вадим Сергеевич",
			BirthDate:              ptrTime(time.Date(1991, 10, 8, 0, 0, 0, 0, time.UTC)),
			Age:                    34,
			Phone:                  "+7 (992) 345-67-89",
			Email:                  "dmitriev.vadim@example.com",
			PassportSeries:         "9900",
			PassportNumber:         "223344",
			PassportIssueDate:      ptrTime(time.Date(2021, 3, 18, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "567-890",
			RegistrationAddress:    "г. Воронеж, ул. 9 Января, д. 45",
			ResidenceAddress:       "г. Воронеж, ул. 9 Января, д. 45",
			RequestedAmount:        1800000,
			CreditTerm:             48,
			CreditType:             "АК",
			MonthlyIncome:          140000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "АО Стрела",
			Position:               "Ведущий инженер",
			CurrentJobExperience:   "5 лет",
			TotalExperience:        "10 лет",
			Status:                 "approved",
			Priority:               "medium",
			CreditScore:            750,
			TotalCredits:           2,
			ActiveCredits:          1,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              300000,
			DTIRatio:               0.18,
			AvailableCreditLimit:   400000,
			ActiveCreditsList:      "[{\"type\":\"Потребительский кредит\",\"amount\":300000,\"monthlyPayment\":10000}]",
			ApprovedAmount:         1200000,
			InitialScore:           780,
			CreditHistoryScore:     74,
			IncomeStabilityScore:   82,
			DebtBurdenScore:        76,
			AgeFactorScore:         78,
			EmploymentScore:        85,
			SolvabilityScore:       80,
			RiskScore:              78,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "ПК-88990011-13-13",
			ClientName:             "Жукова Ольга Викторовна",
			FullName:               "Жукова Ольга Викторовна",
			BirthDate:              ptrTime(time.Date(1989, 3, 22, 0, 0, 0, 0, time.UTC)),
			Age:                    37,
			Phone:                  "+7 (993) 456-78-90",
			Email:                  "zhukova.olga@example.com",
			PassportSeries:         "0011",
			PassportNumber:         "445566",
			PassportIssueDate:      ptrTime(time.Date(2019, 7, 12, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "678-901",
			RegistrationAddress:    "г. Калининград, ул. Артиллерийская, д. 28",
			ResidenceAddress:       "г. Калининград, ул. Артиллерийская, д. 28",
			RequestedAmount:        600000,
			CreditTerm:             24,
			CreditType:             "ПК",
			MonthlyIncome:          80000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "АО Комета",
			Position:               "Экономист",
			CurrentJobExperience:   "4 года",
			TotalExperience:        "9 лет",
			Status:                 "new",
			Priority:               "medium",
			CreditScore:            700,
			TotalCredits:           1,
			ActiveCredits:          0,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              0,
			DTIRatio:               0.15,
			AvailableCreditLimit:   220000,
			ActiveCreditsList:      "[]",
			ApprovedAmount:         0,
			InitialScore:           730,
			CreditHistoryScore:     68,
			IncomeStabilityScore:   75,
			DebtBurdenScore:        70,
			AgeFactorScore:         75,
			EmploymentScore:        80,
			SolvabilityScore:       72,
			RiskScore:              72,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-2 * 24 * time.Hour),
		},
		{
			ID:                     "БК-99001122-14-14",
			ClientName:             "Егоров Денис Александрович",
			FullName:               "Егоров Денис Александрович",
			BirthDate:              ptrTime(time.Date(1987, 12, 3, 0, 0, 0, 0, time.UTC)),
			Age:                    38,
			Phone:                  "+7 (994) 567-89-01",
			Email:                  "egorov.denis@example.com",
			PassportSeries:         "2233",
			PassportNumber:         "556677",
			PassportIssueDate:      ptrTime(time.Date(2017, 5, 20, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "789-012",
			RegistrationAddress:    "г. Тюмень, ул. Республики, д. 35",
			ResidenceAddress:       "г. Тюмень, ул. Республики, д. 35",
			RequestedAmount:        2500000,
			CreditTerm:             30,
			CreditType:             "БК",
			MonthlyIncome:          180000,
			EmploymentStatus:       "Индивидуальный предприниматель",
			EmployerName:           "ИП Егоров Д.А.",
			Position:               "Директор",
			CurrentJobExperience:   "8 лет",
			TotalExperience:        "12 лет",
			Status:                 "approved",
			Priority:               "medium",
			CreditScore:            750,
			TotalCredits:           2,
			ActiveCredits:          1,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              300000,
			DTIRatio:               0.18,
			AvailableCreditLimit:   400000,
			ActiveCreditsList:      "[{\"type\":\"Потребительский кредит\",\"amount\":300000,\"monthlyPayment\":10000}]",
			ApprovedAmount:         1200000,
			InitialScore:           780,
			CreditHistoryScore:     74,
			IncomeStabilityScore:   82,
			DebtBurdenScore:        76,
			AgeFactorScore:         78,
			EmploymentScore:        85,
			SolvabilityScore:       80,
			RiskScore:              78,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "ПК-88990011-13-13",
			ClientName:             "Жукова Ольга Викторовна",
			FullName:               "Жукова Ольга Викторовна",
			BirthDate:              ptrTime(time.Date(1988, 8, 15, 0, 0, 0, 0, time.UTC)),
			Age:                    37,
			Phone:                  "+7 (985) 678-90-12",
			Email:                  "zhukova.olga@example.com",
			PassportSeries:         "7890",
			PassportNumber:         "123456",
			PassportIssueDate:      ptrTime(time.Date(2019, 7, 10, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "456-789",
			RegistrationAddress:    "г. Казань, ул. Баумана, д. 22",
			ResidenceAddress:       "г. Казань, ул. Баумана, д. 22",
			RequestedAmount:        700000,
			CreditTerm:             24,
			CreditType:             "ПК",
			MonthlyIncome:          85000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "ИП Егоров Д.А.",
			Position:               "Директор",
			CurrentJobExperience:   "8 лет",
			TotalExperience:        "12 лет",
			Status:                 "approved",
			Priority:               "high",
			CreditScore:            770,
			TotalCredits:           3,
			ActiveCredits:          2,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              900000,
			DTIRatio:               0.28,
			AvailableCreditLimit:   500000,
			ActiveCreditsList:      "[{\"type\":\"Бизнес-кредит\",\"amount\":500000,\"monthlyPayment\":20000},{\"type\":\"Овердрафт\",\"amount\":400000,\"monthlyPayment\":0}]",
			ApprovedAmount:         1800000,
			InitialScore:           800,
			CreditHistoryScore:     78,
			IncomeStabilityScore:   84,
			DebtBurdenScore:        76,
			AgeFactorScore:         74,
			EmploymentScore:        88,
			SolvabilityScore:       80,
			RiskScore:              79,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "ИП-10111223-15-15",
			ClientName:             "Зайцева Татьяна Сергеевна",
			FullName:               "Зайцева Татьяна Сергеевна",
			BirthDate:              ptrTime(time.Date(1984, 7, 16, 0, 0, 0, 0, time.UTC)),
			Age:                    41,
			Phone:                  "+7 (995) 678-90-12",
			Email:                  "zayceva.tatiana@example.com",
			PassportSeries:         "3344",
			PassportNumber:         "667788",
			PassportIssueDate:      ptrTime(time.Date(2016, 9, 8, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "012-345",
			RegistrationAddress:    "г. Омск, ул. Дзержинского, д. 60",
			ResidenceAddress:       "г. Омск, ул. Дзержинского, д. 60",
			RequestedAmount:        6000000,
			CreditTerm:             240,
			CreditType:             "ИП",
			MonthlyIncome:          220000,
			EmploymentStatus:       "Руководитель",
			EmployerName:           "ООО Сатурн",
			Position:               "Генеральный директор",
			CurrentJobExperience:   "10 лет",
			TotalExperience:        "20 лет",
			Status:                 "approved",
			Priority:               "high",
			CreditScore:            840,
			TotalCredits:           2,
			ActiveCredits:          1,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              1500000,
			DTIRatio:               0.25,
			AvailableCreditLimit:   1000000,
			ActiveCreditsList:      "[{\"type\":\"Ипотека\",\"amount\":1500000,\"monthlyPayment\":65000}]",
			ApprovedAmount:         4500000,
			InitialScore:           870,
			CreditHistoryScore:     88,
			IncomeStabilityScore:   92,
			DebtBurdenScore:        82,
			AgeFactorScore:         70,
			EmploymentScore:        96,
			SolvabilityScore:       88,
			RiskScore:              85,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "ПК-11223344-16-16",
			ClientName:             "Ильин Андрей Вячеславович",
			FullName:               "Ильин Андрей Вячеславович",
			BirthDate:              ptrTime(time.Date(1994, 4, 27, 0, 0, 0, 0, time.UTC)),
			Age:                    31,
			Phone:                  "+7 (996) 789-01-23",
			Email:                  "ilya.andrey@example.com",
			PassportSeries:         "4455",
			PassportNumber:         "778900",
			PassportIssueDate:      ptrTime(time.Date(2022, 6, 15, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "234-567",
			RegistrationAddress:    "г. Волгоград, ул. Рабочая, д. 22",
			ResidenceAddress:       "г. Волгоград, ул. Рабочая, д. 22",
			RequestedAmount:        400000,
			CreditTerm:             18,
			CreditType:             "ПК",
			MonthlyIncome:          60000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "АО Юпитер",
			Position:               "Специалист",
			CurrentJobExperience:   "2 года",
			TotalExperience:        "5 лет",
			Status:                 "new",
			Priority:               "low",
			CreditScore:            660,
			TotalCredits:           0,
			ActiveCredits:          0,
			ClosedCredits:          0,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              0,
			DTIRatio:               0.12,
			AvailableCreditLimit:   120000,
			ActiveCreditsList:      "[]",
			ApprovedAmount:         0,
			InitialScore:           690,
			CreditHistoryScore:     60,
			IncomeStabilityScore:   65,
			DebtBurdenScore:        68,
			AgeFactorScore:         85,
			EmploymentScore:        70,
			SolvabilityScore:       65,
			RiskScore:              65,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "КК-12334455-17-17",
			ClientName:             "Кузнецова Елена Николаевна",
			FullName:               "Кузнецова Елена Николаевна",
			BirthDate:              ptrTime(time.Date(1987, 11, 9, 0, 0, 0, 0, time.UTC)),
			Age:                    38,
			Phone:                  "+7 (997) 890-12-34",
			Email:                  "kuznetsova.elena@example.com",
			PassportSeries:         "5566",
			PassportNumber:         "889011",
			PassportIssueDate:      ptrTime(time.Date(2018, 4, 22, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "345-678",
			RegistrationAddress:    "г. Саратов, ул. Чапаева, д. 48",
			ResidenceAddress:       "г. Саратов, ул. Чапаева, д. 48",
			RequestedAmount:        100000,
			CreditTerm:             6,
			CreditType:             "КК",
			MonthlyIncome:          52000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "ООО Вертикаль",
			Position:               "Кассир",
			CurrentJobExperience:   "3 года",
			TotalExperience:        "8 лет",
			Status:                 "new",
			Priority:               "low",
			CreditScore:            640,
			TotalCredits:           1,
			ActiveCredits:          0,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              0,
			DTIRatio:               0.08,
			AvailableCreditLimit:   100000,
			ActiveCreditsList:      "[]",
			ApprovedAmount:         0,
			InitialScore:           670,
			CreditHistoryScore:     60,
			IncomeStabilityScore:   62,
			DebtBurdenScore:        65,
			AgeFactorScore:         75,
			EmploymentScore:        68,
			SolvabilityScore:       62,
			RiskScore:              62,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "АК-13445566-18-18",
			ClientName:             "Макаров Константин Юрьевич",
			FullName:               "Макаров Константин Юрьевич",
			BirthDate:              ptrTime(time.Date(1982, 6, 14, 0, 0, 0, 0, time.UTC)),
			Age:                    43,
			Phone:                  "+7 (998) 901-23-45",
			Email:                  "makarov.konstantin@example.com",
			PassportSeries:         "6677",
			PassportNumber:         "990122",
			PassportIssueDate:      ptrTime(time.Date(2015, 10, 30, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "456-789",
			RegistrationAddress:    "г. Тольятти, ул. Спортивная, д. 16",
			ResidenceAddress:       "г. Тольятти, ул. Спортивная, д. 16",
			RequestedAmount:        2200000,
			CreditTerm:             48,
			CreditType:             "АК",
			MonthlyIncome:          160000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "АО АвтоВаз",
			Position:               "Начальник цеха",
			CurrentJobExperience:   "15 лет",
			TotalExperience:        "22 года",
			Status:                 "new",
			Priority:               "medium",
			CreditScore:            790,
			TotalCredits:           4,
			ActiveCredits:          2,
			ClosedCredits:          2,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              800000,
			DTIRatio:               0.25,
			AvailableCreditLimit:   350000,
			ActiveCreditsList:      "[{\"type\":\"Автокредит\",\"amount\":400000,\"monthlyPayment\":15000},{\"type\":\"Потребительский кредит\",\"amount\":400000,\"monthlyPayment\":0}]",
			ApprovedAmount:         0,
			InitialScore:           820,
			CreditHistoryScore:     80,
			IncomeStabilityScore:   88,
			DebtBurdenScore:        78,
			AgeFactorScore:         65,
			EmploymentScore:        95,
			SolvabilityScore:       82,
			RiskScore:              81,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-2 * 24 * time.Hour),
		},
		{
			ID:                     "ПК-14556677-19-19",
			ClientName:             "Павлова Мария Дмитриевна",
			FullName:               "Павлова Мария Дмитриевна",
			BirthDate:              ptrTime(time.Date(1996, 2, 20, 0, 0, 0, 0, time.UTC)),
			Age:                    30,
			Phone:                  "+7 (999) 012-34-56",
			Email:                  "pavlova.maria@example.com",
			PassportSeries:         "7788",
			PassportNumber:         "001233",
			PassportIssueDate:      ptrTime(time.Date(2023, 1, 15, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "567-890",
			RegistrationAddress:    "г. Ижевск, ул. Пушкинская, д. 35",
			ResidenceAddress:       "г. Ижевск, ул. Пушкинская, д. 35",
			RequestedAmount:        350000,
			CreditTerm:             15,
			CreditType:             "ПК",
			MonthlyIncome:          48000,
			EmploymentStatus:       "Штатный сотрудник",
			EmployerName:           "ООО Ижмаш",
			Position:               "Оператор",
			CurrentJobExperience:   "1 год",
			TotalExperience:        "3 года",
			Status:                 "new",
			Priority:               "low",
			CreditScore:            620,
			TotalCredits:           0,
			ActiveCredits:          0,
			ClosedCredits:          0,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              0,
			DTIRatio:               0.10,
			AvailableCreditLimit:   80000,
			ActiveCreditsList:      "[]",
			ApprovedAmount:         0,
			InitialScore:           650,
			CreditHistoryScore:     55,
			IncomeStabilityScore:   60,
			DebtBurdenScore:        60,
			AgeFactorScore:         90,
			EmploymentScore:        65,
			SolvabilityScore:       60,
			RiskScore:              60,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
		{
			ID:                     "БК-15667788-20-20",
			ClientName:             "Семенов Никита Игоревич",
			FullName:               "Семенов Никита Игоревич",
			BirthDate:              ptrTime(time.Date(1990, 9, 11, 0, 0, 0, 0, time.UTC)),
			Age:                    35,
			Phone:                  "+7 (900) 123-45-67",
			Email:                  "semenov.nikita@example.com",
			PassportSeries:         "8899",
			PassportNumber:         "112344",
			PassportIssueDate:      ptrTime(time.Date(2019, 12, 5, 0, 0, 0, 0, time.UTC)),
			PassportDepartmentCode: "678-901",
			RegistrationAddress:    "г. Ульяновск, ул. Гончарова, д. 20",
			ResidenceAddress:       "г. Ульяновск, ул. Гончарова, д. 20",
			RequestedAmount:        1800000,
			CreditTerm:             24,
			CreditType:             "БК",
			MonthlyIncome:          130000,
			EmploymentStatus:       "Индивидуальный предприниматель",
			EmployerName:           "ИП Семенов Н.И.",
			Position:               "Предприниматель",
			CurrentJobExperience:   "5 лет",
			TotalExperience:        "8 лет",
			Status:                 "new",
			Priority:               "medium",
			CreditScore:            730,
			TotalCredits:           2,
			ActiveCredits:          1,
			ClosedCredits:          1,
			DelayedPayments12m:     0,
			CurrentDelinquencies:   false,
			MaxDelinquencyDays:     0,
			TotalDebt:              500000,
			DTIRatio:               0.22,
			AvailableCreditLimit:   300000,
			ActiveCreditsList:      "[{\"type\":\"Оборотный кредит\",\"amount\":500000,\"monthlyPayment\":25000}]",
			ApprovedAmount:         0,
			InitialScore:           760,
			CreditHistoryScore:     72,
			IncomeStabilityScore:   78,
			DebtBurdenScore:        74,
			AgeFactorScore:         78,
			EmploymentScore:        80,
			SolvabilityScore:       75,
			RiskScore:              74,
			AIRecommendation:       "approve",
			CreatedAt:              time.Now().Add(-1 * 24 * time.Hour),
		},
	}

	for _, app := range testApplications {
		var existingApp models.CreditApplication
		result := db.Where("id = ?", app.ID).First(&existingApp)

		if result.Error != nil {
			app.AddActionToHistory("created", "Система", "Создание заявки")

			switch app.Status {
			case "in_review":
				app.AddActionToHistory("started_review", "Аналитик Иванов И.И.", "Начало проверки заявки")
			case "approved":
				app.AddActionToHistory("started_review", "Аналитик Петров П.П.", "Начало проверки заявки")
				app.AddActionToHistory("decision_made", "Аналитик Петров П.П.", "Одобрение заявки")
			case "rejected":
				app.AddActionToHistory("started_review", "Аналитик Сидоров С.С.", "Начало проверки заявки")
				app.AddActionToHistory("decision_made", "Аналитик Сидоров С.С.", "Отклонение заявки")
			}

			if err := db.Create(&app).Error; err != nil {
				log.Printf("Error creating test application %s: %v", app.ID, err)
			} else {
				log.Printf("Created test application: %s", app.ID)
			}
		}
	}

	log.Println("Test applications creation completed")
}

func ptrTime(t time.Time) *time.Time {
	return &t
}
